/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;
import org.apache.commons.cli.*;

public class App {
    public static void main(String[] args) {


        Options options = new Options();
        options.addOption("h","help",false,"print usage message");
        options.addOption("b","batch",true,"batch files containing expressions to evaluate");
        options.addOption("o","output",true,"output file");

        CommandLineParser parser = new DefaultParser();

        try {
            CommandLine cmd = parser.parse(options, args);
            if(cmd.hasOption("h")) {
                help();
            } else if(cmd.hasOption("b")) {
                batch(args);
            } else if(cmd.hasOption("o")) {
                output(args);
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }

    }

    public static void batch(String[] args){
        String lib = args[1];
        System.out.println("Batch value: " + lib);
    }

    public static void output(String[] args){
        String lib = args[1];
        System.out.println("Output value: " + lib);
    }

    public static void help(){
        System.out.println("usage: eval [OPTIONS]\n" +
                "Evaluation of simple mathematical expressions\n" +
                "\n" +
                "-b, --batch <file>\tbatch file containing expressions to evaluate\n" +
                "-h, --help\tprint usage message\n" +
                "-o, --output <file>\toutput file\n" +
                "\n" +
                "Copyright (C) 2021 David L. Lape");
    }
}
